#!/usr/bin/env python3
"""Generate localized English/French UI pages from the Japanese sources.

Pages:
- /en/wine/search/
- /fr/wine/search/
- /en/wine/plans/
- /fr/wine/plans/
- /en/wine/mypage/
- /fr/wine/mypage/
"""

from pathlib import Path

BASE = Path(__file__).resolve().parent.parent


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def replace_many(text: str, replacements):
    for old, new in replacements:
        text = text.replace(old, new)
    return text


SEARCH_COMMON = [
    ('<html lang="ja">', '<html lang="{lang}">'),
    ('<title>ワイナリー検索 — 全国432ワイナリー | Terroir HUB WINE</title>', '{title}'),
    ('<meta name="description" content="全国432ワイナリーを地域・品種・キーワードで検索。北海道から九州まで、日本ワインの造り手をTerroir HUB WINEで探せます。保存はマイページ、深掘りはSakuraで。">', '{desc}'),
    ('<link rel="canonical" href="https://wine.terroirhub.com/wine/search/">', '{canonical}'),
    ('<link rel="alternate" hreflang="ja" href="https://wine.terroirhub.com/wine/search/">\n<link rel="alternate" hreflang="en" href="https://wine.terroirhub.com/en/wine/search/">\n<link rel="alternate" hreflang="fr" href="https://wine.terroirhub.com/fr/wine/search/">\n', '{hreflangs}'),
    ('<a href="/" class="nav-back">&#8592; トップへ</a>', '{back_link}'),
    ('<a href="/wine/mypage/" class="nav-page">マイページ</a>', '{mypage_link}'),
    ('<h1>ワイナリー検索</h1>', '{h1}'),
    ('<p>全国432ワイナリーを、キーワード・地域・品種で探すページです。検索した候補はマイページに保存でき、Sakuraは会話の深掘りで使います。</p>', '{lead}'),
    ('<span>ログイン無料</span>', '{pill1}'),
    ('<span>マイページで保存</span>', '{pill2}'),
    ('<span>Sakuraは月額課金</span>', '{pill3}'),
    ('<a href="/wine/guide/beginner.html">初心者ガイド</a>', '{guide1}'),
    ('<a href="/wine/guide/compare.html">比較ハブ</a>', '{guide2}'),
    ('<a href="/wine/guide/visit.html">見学ガイド</a>', '{guide3}'),
    ('<img src="/img/winery-mountain-filled.jpg" alt="ワイナリーの風景">', '{hero_img}'),
    ('候補を探して、保存して、あとから比較するための検索導線を最短にしています。', '{hero_caption}'),
    ('<strong>432</strong><span>ワイナリー収録</span>', '{stat1}'),
    ('<strong>3</strong><span>軸検索対応</span>', '{stat2}'),
    ('<strong>1</strong><span>マイページ保存</span>', '{stat3}'),
    ('<button class="search-btn" onclick="doSearch()">検索</button>', '{search_btn}'),
    ('<option value="">すべての地域</option>', '{region_all}'),
    ('<option value="北海道">北海道</option>', '{region_hokkaido}'),
    ('<option value="東北">東北（山形・岩手・青森）</option>', '{region_tohoku}'),
    ('<option value="山梨">山梨</option>', '{region_yamanashi}'),
    ('<option value="長野">長野</option>', '{region_nagano}'),
    ('<option value="新潟">新潟</option>', '{region_niigata}'),
    ('<option value="近畿">近畿（大阪・京都・兵庫）</option>', '{region_kinki}'),
    ('<option value="中国">中国（島根・岡山・広島・山口）</option>', '{region_chugoku}'),
    ('<option value="四国">四国</option>', '{region_shikoku}'),
    ('<option value="九州">九州（宮崎・熊本・大分）</option>', '{region_kyushu}'),
    ('<option value="">すべての品種</option>', '{variety_all}'),
    ('<option value="甲州">甲州</option>', '{variety1}'),
    ('<option value="マスカット・ベーリーA">マスカット・ベーリーA</option>', '{variety2}'),
    ('<option value="ピノ・ノワール">ピノ・ノワール</option>', '{variety3}'),
    ('<option value="シャルドネ">シャルドネ</option>', '{variety4}'),
    ('<option value="メルロー">メルロー</option>', '{variety5}'),
    ('<option value="カベルネ・ソーヴィニヨン">カベルネ・ソーヴィニヨン</option>', '{variety6}'),
    ('<option value="ケルナー">ケルナー</option>', '{variety7}'),
    ('<option value="デラウェア">デラウェア</option>', '{variety8}'),
    ('<div style="font-size:12px;color:#aaa;margin-bottom:8px;">地域で絞り込む</div>', '{region_label}'),
    ('<span class="region-tag" onclick="setRegion(\'北海道\')">北海道</span>', '{tag1}'),
    ('<span class="region-tag" onclick="setRegion(\'東北\')">東北</span>', '{tag2}'),
    ('<span class="region-tag" onclick="setRegion(\'山梨\')">山梨</span>', '{tag3}'),
    ('<span class="region-tag" onclick="setRegion(\'長野\')">長野</span>', '{tag4}'),
    ('<span class="region-tag" onclick="setRegion(\'新潟\')">新潟</span>', '{tag5}'),
    ('<span class="region-tag" onclick="setRegion(\'近畿\')">近畿</span>', '{tag6}'),
    ('<span class="region-tag" onclick="setRegion(\'中国\')">中国</span>', '{tag7}'),
    ('<span class="region-tag" onclick="setRegion(\'四国\')">四国</span>', '{tag8}'),
    ('<span class="region-tag" onclick="setRegion(\'九州\')">九州</span>', '{tag9}'),
    ('<span>例: 甲州で探す</span>', '{hint1}'),
    ('<span>例: 見学できる場所</span>', '{hint2}'),
    ('<a href="/wine/guide/koshu.html">甲州の入口</a>', '{hint3}'),
    ('<a href="/wine/guide/yamanashi-vs-nagano.html">山梨 vs 長野</a>', '{hint4}'),
    ('<div class="results-info" id="resultsInfo">キーワードを入力するか、地域タグを選択してください</div>', '{results_info}'),
    ('<p>&#127863; 検索してワイナリーを見つけましょう</p>', '{empty1}'),
    ('<p style="font-size:13px;">432ワイナリーから探せます</p>', '{empty2}'),
    ('<p>該当するワイナリーが見つかりませんでした</p>', '{no_results1}'),
    ('<p style="font-size:13px;">別のキーワードや地域でお試しください</p>', '{no_results2}'),
    ('<script type="application/ld+json">\n{\n  "@context": "https://schema.org",\n  "@type": "WebPage",\n  "name": "ワイナリー検索 | Terroir HUB WINE",\n  "description": "全国432ワイナリーを地域・品種・キーワードで検索できるページです。",\n  "url": "https://wine.terroirhub.com/wine/search/",\n  "isPartOf": {\n    "@type": "WebSite",\n    "name": "Terroir HUB WINE",\n    "url": "https://wine.terroirhub.com/"\n  }\n}\n</script>', '{jsonld}'),
    ('<a href="/">ホーム</a>', '{footer_home}'),
    ('<a href="/wine/region/hokkaido.html">北海道</a>', '{footer_hokkaido}'),
    ('<a href="/wine/region/kanto.html">山梨・長野</a>', '{footer_kanto}'),
    ('<a href="/wine/region/kyushu.html">九州</a>', '{footer_kyushu}'),
    ('<a href="/privacy.html">プライバシー</a>', '{footer_privacy}'),
    ('<a href="/terms.html">利用規約</a>', '{footer_terms}'),
    ('<a href="/tokushoho.html">特商法</a>', '{footer_tokusho}'),
    ('<p class="footer-copy">&copy; 2026 合同会社FOMUS — Terroir HUB WINE</p>', '{footer_copy}'),
    ("alert('マイページに保存しました');", "{save_alert}"),
    ("'ワイナリー名・地名・品種で検索…'", "'{placeholder}'"),
    ("document.getElementById('resultsInfo').textContent = 'キーワードを入力するか、地域タグを選択してください';", "{js_results_info}"),
    ("document.getElementById('resultGrid').innerHTML = '<div class=\"empty-state\"><p>&#127863; 検索してワイナリーを見つけましょう</p><p style=\"font-size:13px;\">432ワイナリーから探せます</p></div>';", "{js_empty}"),
    ("grid.innerHTML = '<div class=\"empty-state\"><p>該当するワイナリーが見つかりませんでした</p><p style=\"font-size:13px;\">別のキーワードや地域でお試しください</p></div>';", "{js_no_results}"),
    ("info.innerHTML = '検索結果: <span>0件</span>';","{js_zero_results}"),
    ("info.innerHTML = '検索結果: <span>' + data.length + '件</span>';","{js_count_results}"),
    ("document.getElementById('searchInput').addEventListener('input', debounce(doSearch, 250));", "{input_listener}"),
    ("document.getElementById('searchInput').addEventListener('keydown', e => { if(e.key === 'Enter') doSearch(); });", "{enter_listener}"),
    ("const RECENT_KEY = 'thub_wine_recent_searches';", "{recent_key}"),
    ("const FAVORITES_KEY = 'thub_wine_favorites';", "{favorites_key}"),
    ("showToast('マイページに保存しました');", "{toast_saved}"),
    ("<meta name=\"theme-color\" content=\"#722F37\">", ""),
]


def build_search(lang: str) -> str:
    src = read(BASE / "wine" / "search" / "index.html")
    if lang == "en":
        data = {
            "lang": "en",
            "title": "<title>Winery Search — 432 Wineries | Terroir HUB WINE</title>",
            "desc": '<meta name="description" content="Search 432 Japanese wineries by region, grape variety, or keyword. Save favorites to My Page and use Sakura for deeper exploration.">',
            "canonical": '<link rel="canonical" href="https://wine.terroirhub.com/en/wine/search/">',
            "hreflangs": '<link rel="alternate" hreflang="ja" href="https://wine.terroirhub.com/wine/search/">\n<link rel="alternate" hreflang="en" href="https://wine.terroirhub.com/en/wine/search/">\n<link rel="alternate" hreflang="fr" href="https://wine.terroirhub.com/fr/wine/search/">\n',
            "back_link": '<a href="/en/" class="nav-back">&#8592; Home</a>',
            "mypage_link": '<a href="/en/wine/mypage/" class="nav-page">My Page</a>',
            "h1": '<h1>Winery Search</h1>',
            "lead": '<p>Search 432 Japanese wineries by keyword, region, or grape variety. Save candidates to My Page and use Sakura for deeper conversation.</p>',
            "pill1": '<span>Free login</span>',
            "pill2": '<span>Save in My Page</span>',
            "pill3": '<span>Sakura is monthly</span>',
            "guide1": '<a href="/en/wine/guide/beginner.html">Beginner guide</a>',
            "guide2": '<a href="/en/wine/guide/compare.html">Compare hub</a>',
            "guide3": '<a href="/en/wine/guide/visit.html">Visit guide</a>',
            "hero_img": '<img src="/img/winery-mountain-filled.jpg" alt="Japanese winery landscape">',
            "hero_caption": "We keep search, saving, and comparison tightly connected.",
            "stat1": '<strong>432</strong><span>wineries</span>',
            "stat2": '<strong>3</strong><span>search axes</span>',
            "stat3": '<strong>1</strong><span>My Page save</span>',
            "search_btn": '<button class="search-btn" onclick="doSearch()">Search</button>',
            "region_all": '<option value="">All regions</option>',
            "region_hokkaido": '<option value="北海道">Hokkaido</option>',
            "region_tohoku": '<option value="東北">Tohoku (Yamagata / Iwate / Aomori)</option>',
            "region_yamanashi": '<option value="山梨">Yamanashi</option>',
            "region_nagano": '<option value="長野">Nagano</option>',
            "region_niigata": '<option value="新潟">Niigata</option>',
            "region_kinki": '<option value="近畿">Kinki (Osaka / Kyoto / Hyogo)</option>',
            "region_chugoku": '<option value="中国">Chugoku (Shimane / Okayama / Hiroshima / Yamaguchi)</option>',
            "region_shikoku": '<option value="四国">Shikoku</option>',
            "region_kyushu": '<option value="九州">Kyushu (Miyazaki / Kumamoto / Oita)</option>',
            "variety_all": '<option value="">All grapes</option>',
            "variety1": '<option value="甲州">Koshu</option>',
            "variety2": '<option value="マスカット・ベーリーA">Muscat Bailey A</option>',
            "variety3": '<option value="ピノ・ノワール">Pinot Noir</option>',
            "variety4": '<option value="シャルドネ">Chardonnay</option>',
            "variety5": '<option value="メルロー">Merlot</option>',
            "variety6": '<option value="カベルネ・ソーヴィニヨン">Cabernet Sauvignon</option>',
            "variety7": '<option value="ケルナー">Kerner</option>',
            "variety8": '<option value="デラウェア">Delaware</option>',
            "region_label": '<div style="font-size:12px;color:#aaa;margin-bottom:8px;">Filter by region</div>',
            "tag1": '<span class="region-tag" onclick="setRegion(\'北海道\')">Hokkaido</span>',
            "tag2": '<span class="region-tag" onclick="setRegion(\'東北\')">Tohoku</span>',
            "tag3": '<span class="region-tag" onclick="setRegion(\'山梨\')">Yamanashi</span>',
            "tag4": '<span class="region-tag" onclick="setRegion(\'長野\')">Nagano</span>',
            "tag5": '<span class="region-tag" onclick="setRegion(\'新潟\')">Niigata</span>',
            "tag6": '<span class="region-tag" onclick="setRegion(\'近畿\')">Kinki</span>',
            "tag7": '<span class="region-tag" onclick="setRegion(\'中国\')">Chugoku</span>',
            "tag8": '<span class="region-tag" onclick="setRegion(\'四国\')">Shikoku</span>',
            "tag9": '<span class="region-tag" onclick="setRegion(\'九州\')">Kyushu</span>',
            "hint1": '<span>e.g. search Koshu</span>',
            "hint2": '<span>e.g. visit-friendly places</span>',
            "hint3": '<a href="/en/wine/guide/koshu.html">Koshu entry</a>',
            "hint4": '<a href="/en/wine/guide/yamanashi-vs-nagano.html">Yamanashi vs Nagano</a>',
            "results_info": '<div class="results-info" id="resultsInfo">Type a keyword or choose a region tag</div>',
            "empty1": '<p>&#127863; Search and find wineries</p>',
            "empty2": '<p style="font-size:13px;">432 wineries available</p>',
            "no_results1": '<p>No wineries matched your search</p>',
            "no_results2": '<p style="font-size:13px;">Try a different keyword or region</p>',
            "jsonld": '<script type="application/ld+json">\n{\n  "@context": "https://schema.org",\n  "@type": "WebPage",\n  "name": "Winery Search | Terroir HUB WINE",\n  "description": "Search 432 Japanese wineries by region, grape variety, or keyword.",\n  "url": "https://wine.terroirhub.com/en/wine/search/",\n  "isPartOf": {\n    "@type": "WebSite",\n    "name": "Terroir HUB WINE",\n    "url": "https://wine.terroirhub.com/"\n  }\n}\n</script>',
            "footer_home": '<a href="/en/">Home</a>',
            "footer_hokkaido": '<a href="/en/wine/region/hokkaido.html">Hokkaido</a>',
            "footer_kanto": '<a href="/en/wine/region/kanto.html">Yamanashi / Nagano</a>',
            "footer_kyushu": '<a href="/en/wine/region/kyushu.html">Kyushu</a>',
            "footer_privacy": '<a href="/privacy.html">Privacy</a>',
            "footer_terms": '<a href="/terms.html">Terms</a>',
            "footer_tokusho": '<a href="/tokushoho.html">Legal notice</a>',
            "footer_copy": '<p class="footer-copy">&copy; 2026 FOMUS LLC — Terroir HUB WINE</p>',
            "save_alert": "",
            "placeholder": "Winery name, place, or grape",
            "js_results_info": "document.getElementById('resultsInfo').textContent = 'Type a keyword or choose a region tag';",
            "js_empty": "document.getElementById('resultGrid').innerHTML = '<div class=\"empty-state\"><p>&#127863; Search and find wineries</p><p style=\"font-size:13px;\">432 wineries available</p></div>';",
            "js_no_results": "grid.innerHTML = '<div class=\"empty-state\"><p>No wineries matched your search</p><p style=\"font-size:13px;\">Try a different keyword or region</p></div>';",
            "js_zero_results": "info.innerHTML = 'Results: <span>0</span>';",
            "js_count_results": "info.innerHTML = 'Results: <span>' + data.length + '</span>';",
            "input_listener": "document.getElementById('searchInput').addEventListener('input', debounce(doSearch, 250));",
            "enter_listener": "document.getElementById('searchInput').addEventListener('keydown', e => { if(e.key === 'Enter') doSearch(); });",
            "recent_key": "const RECENT_KEY = 'thub_wine_recent_searches';",
            "favorites_key": "const FAVORITES_KEY = 'thub_wine_favorites';",
            "toast_saved": "showToast('Saved to My Page');",
        }
    else:
        data = {
            "lang": "fr",
            "title": "<title>Recherche de domaines — 432 domaines | Terroir HUB WINE</title>",
            "desc": '<meta name="description" content="Recherchez 432 domaines viticoles japonais par région, cépage ou mot-clé. Enregistrez vos favoris dans Mon espace et approfondissez avec Sakura.">',
            "canonical": '<link rel="canonical" href="https://wine.terroirhub.com/fr/wine/search/">',
            "hreflangs": '<link rel="alternate" hreflang="ja" href="https://wine.terroirhub.com/wine/search/">\n<link rel="alternate" hreflang="en" href="https://wine.terroirhub.com/en/wine/search/">\n<link rel="alternate" hreflang="fr" href="https://wine.terroirhub.com/fr/wine/search/">\n',
            "back_link": '<a href="/fr/" class="nav-back">&#8592; Accueil</a>',
            "mypage_link": '<a href="/fr/wine/mypage/" class="nav-page">Mon espace</a>',
            "h1": '<h1>Recherche de domaines</h1>',
            "lead": '<p>Recherchez 432 domaines viticoles japonais par mot-clé, région ou cépage. Enregistrez vos favoris dans Mon espace et utilisez Sakura pour aller plus loin.</p>',
            "pill1": '<span>Connexion gratuite</span>',
            "pill2": '<span>Sauvegarde dans Mon espace</span>',
            "pill3": '<span>Sakura en abonnement</span>',
            "guide1": '<a href="/fr/wine/guide/beginner.html">Guide débutant</a>',
            "guide2": '<a href="/fr/wine/guide/compare.html">Hub comparatif</a>',
            "guide3": '<a href="/fr/wine/guide/visit.html">Guide visite</a>',
            "hero_img": '<img src="/img/winery-mountain-filled.jpg" alt="Paysage de domaine japonais">',
            "hero_caption": "Recherche, sauvegarde et comparaison sont étroitement liées.",
            "stat1": '<strong>432</strong><span>domaines</span>',
            "stat2": '<strong>3</strong><span>axes de recherche</span>',
            "stat3": '<strong>1</strong><span>sauvegarde</span>',
            "search_btn": '<button class="search-btn" onclick="doSearch()">Rechercher</button>',
            "region_all": '<option value="">Toutes les régions</option>',
            "region_hokkaido": '<option value="北海道">Hokkaido</option>',
            "region_tohoku": '<option value="東北">Tôhoku (Yamagata / Iwate / Aomori)</option>',
            "region_yamanashi": '<option value="山梨">Yamanashi</option>',
            "region_nagano": '<option value="長野">Nagano</option>',
            "region_niigata": '<option value="新潟">Niigata</option>',
            "region_kinki": '<option value="近畿">Kinki (Osaka / Kyoto / Hyogo)</option>',
            "region_chugoku": '<option value="中国">Chûgoku (Shimane / Okayama / Hiroshima / Yamaguchi)</option>',
            "region_shikoku": '<option value="四国">Shikoku</option>',
            "region_kyushu": '<option value="九州">Kyushu (Miyazaki / Kumamoto / Oita)</option>',
            "variety_all": '<option value="">Tous les cépages</option>',
            "variety1": '<option value="甲州">Koshu</option>',
            "variety2": '<option value="マスカット・ベーリーA">Muscat Bailey A</option>',
            "variety3": '<option value="ピノ・ノワール">Pinot Noir</option>',
            "variety4": '<option value="シャルドネ">Chardonnay</option>',
            "variety5": '<option value="メルロー">Merlot</option>',
            "variety6": '<option value="カベルネ・ソーヴィニヨン">Cabernet Sauvignon</option>',
            "variety7": '<option value="ケルナー">Kerner</option>',
            "variety8": '<option value="デラウェア">Delaware</option>',
            "region_label": '<div style="font-size:12px;color:#aaa;margin-bottom:8px;">Filtrer par région</div>',
            "tag1": '<span class="region-tag" onclick="setRegion(\'北海道\')">Hokkaido</span>',
            "tag2": '<span class="region-tag" onclick="setRegion(\'東北\')">Tôhoku</span>',
            "tag3": '<span class="region-tag" onclick="setRegion(\'山梨\')">Yamanashi</span>',
            "tag4": '<span class="region-tag" onclick="setRegion(\'長野\')">Nagano</span>',
            "tag5": '<span class="region-tag" onclick="setRegion(\'新潟\')">Niigata</span>',
            "tag6": '<span class="region-tag" onclick="setRegion(\'近畿\')">Kinki</span>',
            "tag7": '<span class="region-tag" onclick="setRegion(\'中国\')">Chûgoku</span>',
            "tag8": '<span class="region-tag" onclick="setRegion(\'四国\')">Shikoku</span>',
            "tag9": '<span class="region-tag" onclick="setRegion(\'九州\')">Kyushu</span>',
            "hint1": '<span>ex. chercher Koshu</span>',
            "hint2": '<span>ex. domaines visitables</span>',
            "hint3": '<a href="/fr/wine/guide/koshu.html">Entrée Koshu</a>',
            "hint4": '<a href="/fr/wine/guide/yamanashi-vs-nagano.html">Yamanashi vs Nagano</a>',
            "results_info": '<div class="results-info" id="resultsInfo">Saisissez un mot-clé ou choisissez une région</div>',
            "empty1": '<p>&#127863; Recherchez et trouvez des domaines</p>',
            "empty2": '<p style="font-size:13px;">432 domaines disponibles</p>',
            "no_results1": '<p>Aucun domaine trouvé</p>',
            "no_results2": '<p style="font-size:13px;">Essayez un autre mot-clé ou une autre région</p>',
            "jsonld": '<script type="application/ld+json">\n{\n  "@context": "https://schema.org",\n  "@type": "WebPage",\n  "name": "Recherche de domaines | Terroir HUB WINE",\n  "description": "Recherchez 432 domaines viticoles japonais par région, cépage ou mot-clé.",\n  "url": "https://wine.terroirhub.com/fr/wine/search/",\n  "isPartOf": {\n    "@type": "WebSite",\n    "name": "Terroir HUB WINE",\n    "url": "https://wine.terroirhub.com/"\n  }\n}\n</script>',
            "footer_home": '<a href="/fr/">Accueil</a>',
            "footer_hokkaido": '<a href="/fr/wine/region/hokkaido.html">Hokkaido</a>',
            "footer_kanto": '<a href="/fr/wine/region/kanto.html">Yamanashi / Nagano</a>',
            "footer_kyushu": '<a href="/fr/wine/region/kyushu.html">Kyushu</a>',
            "footer_privacy": '<a href="/privacy.html">Confidentialité</a>',
            "footer_terms": '<a href="/terms.html">Conditions</a>',
            "footer_tokusho": '<a href="/tokushoho.html">Mentions légales</a>',
            "footer_copy": '<p class="footer-copy">&copy; 2026 FOMUS LLC — Terroir HUB WINE</p>',
            "save_alert": "",
            "placeholder": "Nom du domaine, lieu ou cépage",
            "js_results_info": "document.getElementById('resultsInfo').textContent = 'Saisissez un mot-clé ou choisissez une région';",
            "js_empty": "document.getElementById('resultGrid').innerHTML = '<div class=\"empty-state\"><p>&#127863; Recherchez et trouvez des domaines</p><p style=\"font-size:13px;\">432 domaines disponibles</p></div>';",
            "js_no_results": "grid.innerHTML = '<div class=\"empty-state\"><p>Aucun domaine trouvé</p><p style=\"font-size:13px;\">Essayez un autre mot-clé ou une autre région</p></div>';",
            "js_zero_results": "info.innerHTML = 'Résultats : <span>0</span>';",
            "js_count_results": "info.innerHTML = 'Résultats : <span>' + data.length + '</span>';",
            "input_listener": "document.getElementById('searchInput').addEventListener('input', debounce(doSearch, 250));",
            "enter_listener": "document.getElementById('searchInput').addEventListener('keydown', e => { if(e.key === 'Enter') doSearch(); });",
            "recent_key": "const RECENT_KEY = 'thub_wine_recent_searches';",
            "favorites_key": "const FAVORITES_KEY = 'thub_wine_favorites';",
            "toast_saved": "showToast('Enregistré dans Mon espace');",
        }

    text = src
    for old, new in SEARCH_COMMON:
        text = text.replace(old, new.format(**data))
    # Localize result card strings used inside the JS template output.
    if lang == "en":
        text = text.replace("<a class=\"result-detail\" href=\"' + (w.page || '#') + '\">詳細</a>",
                            "<a class=\"result-detail\" href=\"' + (w.page || '#') + '\">Details</a>")
        text = text.replace(">保存</button>", ">Save</button>")
        text = text.replace("'不明'", "'Unknown'")
    else:
        text = text.replace("<a class=\"result-detail\" href=\"' + (w.page || '#') + '\">詳細</a>",
                            "<a class=\"result-detail\" href=\"' + (w.page || '#') + '\">Détails</a>")
        text = text.replace(">保存</button>", ">Enregistrer</button>")
        text = text.replace("'不明'", "'Non renseigné'")
    text = text.replace("{save_alert}", data["save_alert"])
    text = text.replace("{toast_saved}", data["toast_saved"])
    text = text.replace("{jsonld}", data["jsonld"])
    text = text.replace("{footer_copy}", data["footer_copy"])
    text = text.replace("{js_zero_results}", data["js_zero_results"])
    text = text.replace("{js_count_results}", data["js_count_results"])
    text = text.replace('placeholder="ワイナリー名・地名・品種で検索…"', f'placeholder="{data["placeholder"]}"')
    return text


PLAN_COMMON = [
    ('<html lang="ja">', '<html lang="{lang}">'),
    ('<title>料金プラン — Terroir HUB WINE</title>', '{title}'),
    ('<meta name="description" content="Terroir HUB WINEの料金プラン。ログインとマイページは無料、AIソムリエ「サクラ」は月額課金。日本ワイン432ワイナリーのデータを活用。">', '{desc}'),
    ('<link rel="canonical" href="https://wine.terroirhub.com/wine/plans/">', '{canonical}'),
    ('<a class="nav-logo" href="/">Terroir HUB <em>WINE</em></a>', '{brand_link}'),
    ('<a href="/wine/search/">ワイナリー検索</a>', '{nav_search}'),
    ('<a href="/wine/guide/">ワインガイド</a>', '{nav_guide}'),
    ('<a href="/wine/mypage/">マイページ</a>', '{nav_mypage}'),
    ('<a href="/wine/plans/" class="active">プラン</a>', '{nav_active}'),
    ('<div class="hero-tag">Plans</div>', '{hero_tag}'),
    ('<h1>まずは無料で。<br>もっと使いたくなったら。</h1>', '{hero_h1}'),
    ('<p>登録は無料。AIソムリエ「サクラ」はログイン後に利用可能。短文中心で試して、必要ならすぐアップグレードできます。</p>', '{hero_p}'),
    ('<img src="/img/sakura-fullbody.png" alt="サクラ">', '{sakura_img}'),
    ('<h3>AIソムリエ「サクラ」とは？</h3>', '{sakura_h3}'),
    ('<p>全国432ワイナリーのデータをもとに、品種・産地・ペアリング・ワイナリー紹介まで何でも回答。日本語・英語・フランス語に対応。Terroir HUB全サイト（日本酒・焼酎・ウイスキー）も1アカウントで利用できます。</p>', '{sakura_p}'),
    ('<div class="card-name">Free Login</div>', '{free_name}'),
    ('<div class="card-price">¥0</div>', '{free_price}'),
    ('<div class="card-desc">ログインとマイページが無料</div>', '{free_desc}'),
    ('<li class="on">ログインしてマイページ利用</li>', '{free_li1}'),
    ('<li class="on">保存・最近の検索・再訪問</li>', '{free_li2}'),
    ('<li class="on">ワイナリー検索・ガイド閲覧</li>', '{free_li3}'),
    ('<li class="on">比較ハブの閲覧</li>', '{free_li4}'),
    ('<li class="off">AIサクラの本格相談</li>', '{free_li5}'),
    ('<li class="off">多言語での深掘り</li>', '{free_li6}'),
    ('<li class="off">長文レポート生成</li>', '{free_li7}'),
    ('<li class="off">連続質問の拡張利用</li>', '{free_li8}'),
    ('<button class="card-cta cta-free" onclick="showAuth(\'signup\')">無料で始める</button>', '{free_btn}'),
    ('<div class="card-name">Pro</div>', '{pro_name}'),
    ('<div class="card-price">¥500<span>/月</span></div>', '{pro_price}'),
    ('<div class="card-desc">Sakuraを日常利用する基本プラン</div>', '{pro_desc}'),
    ('<div class="card-highlight">Free Loginの全機能 +</div>', '{pro_high}'),
    ('<li class="on">AIサクラ 月100クレジット</li>', '{pro_li1}'),
    ('<li class="on">英語・フランス語の会話</li>', '{pro_li2}'),
    ('<li class="on">比較とおすすめの深掘り</li>', '{pro_li3}'),
    ('<li class="on">ペアリング・旅の相談</li>', '{pro_li4}'),
    ('<li class="on">ワイナリー比較の保存</li>', '{pro_li5}'),
    ('<li class="on">会話ログの再開</li>', '{pro_li6}'),
    ('<li class="off">長文レポート生成</li>', '{pro_li7}'),
    ('<li class="off">大量利用向けの上位枠</li>', '{pro_li8}'),
    ('<button class="card-cta cta-pro" onclick="if(window.thubAuth&&window.thubAuth.isLoggedIn){thubSubscribe(\'pro\')}else{sessionStorage.setItem(\'thub_pending_plan\',\'pro\');showAuth(\'signup\')}">Proを始める</button>', '{pro_btn}'),
    ('<div class="card-name">Premium</div>', '{premium_name}'),
    ('<div class="card-price">¥1,500<span>/月</span></div>', '{premium_price}'),
    ('<div class="card-desc">Sakuraを多言語で使い倒す</div>', '{premium_desc}'),
    ('<div class="card-highlight">Proの全機能 +</div>', '{premium_high}'),
    ('<li class="on">AIサクラ 月300クレジット</li>', '{premium_li1}'),
    ('<li class="on">ワイナリー詳細レポート生成</li>', '{premium_li2}'),
    ('<li class="on">全ジャンル横断比較</li>', '{premium_li3}'),
    ('<li class="on">深掘り旅程・購入相談</li>', '{premium_li4}'),
    ('<li class="on">追加クレジット購入</li>', '{premium_li5}'),
    ('<li class="on">長文・連続会話の強化</li>', '{premium_li6}'),
    ('<button class="card-cta cta-premium" onclick="if(window.thubAuth&&window.thubAuth.isLoggedIn){thubSubscribe(\'premium\')}else{sessionStorage.setItem(\'thub_pending_plan\',\'premium\');showAuth(\'signup\')}">Premiumを始める</button>', '{premium_btn}'),
    ('<div class="plans-note"><strong>考え方:</strong> ログインは無料、マイページも無料。Sakuraだけを月額課金にして、会話・比較・多言語相談の価値で選ばれる形にしています。1アカウントで日本酒・焼酎・ウイスキー・ワインを横断できます。</div>', '{note}'),
    ('<p class="note">Terroir HUBは日本酒・焼酎・ウイスキー・ワインを1アカウントで利用可能。<a href="https://sake.terroirhub.com">sake.terroirhub.com</a> でのご登録もそのままご利用いただけます。</p>', '{secondary_note}'),
    ('<div class="card-badge">おすすめ</div>', '{badge}'),
    ('<footer class="footer">\n  &copy; 2025 Terroir HUB WINE — 合同会社FOMUS &nbsp;|&nbsp;\n  <a href="/privacy.html">プライバシーポリシー</a> &nbsp;|&nbsp;\n  <a href="/terms.html">利用規約</a>\n</footer>', '{footer}'),
    ('<h2 class="faq-title">よくある質問</h2>', '{faq_title}'),
    ('<div class="faq-q" onclick="this.parentElement.classList.toggle(\'open\')">いつでも解約できますか？</div>', '{faq1q}'),
    ('<div class="faq-a">はい。次回更新日以降の請求は発生しません。当該期間の終了までサービスをご利用いただけます。</div>', '{faq1a}'),
    ('<div class="faq-q" onclick="this.parentElement.classList.toggle(\'open\')">Sakuraは無料で使えますか？</div>', '{faq2q}'),
    ('<div class="faq-a">ログインは無料ですが、Sakuraの本格利用は月額プランです。短い試用は用意しても、価値の中心は有料サブスクに置いています。</div>', '{faq2a}'),
    ('<div class="faq-q" onclick="this.parentElement.classList.toggle(\'open\')">日本酒版と同じアカウントで使えますか？</div>', '{faq3q}'),
    ('<div class="faq-a">はい。Terroir HUBは全サイト（日本酒・焼酎・ウイスキー・ワイン）で1アカウント共通です。どのサイトでログインしていても、そのままワインサイトのサクラを利用できます。クレジットも共通です。</div>', '{faq3a}'),
    ('<div class="faq-q" onclick="this.parentElement.classList.toggle(\'open\')">支払方法は？</div>', '{faq4q}'),
    ('<div class="faq-a">クレジットカード（Visa / Mastercard / Amex / JCB）に対応しています。Stripe経由の安全な決済です。</div>', '{faq4a}'),
    ('<div class="faq-q" onclick="this.parentElement.classList.toggle(\'open\')">プラン変更はできますか？</div>', '{faq5q}'),
    ('<div class="faq-a">はい。アップグレードは即時反映、ダウングレードは次回更新日から切り替わります。</div>', '{faq5a}'),
]


def build_plans(lang: str) -> str:
    src = read(BASE / "wine" / "plans" / "index.html")
    if lang == "en":
        data = {
            "lang": "en",
            "title": "<title>Plans — Terroir HUB WINE</title>",
            "desc": '<meta name="description" content="Terroir HUB WINE pricing. Login and My Page are free; AI sommelier Sakura is monthly subscription. Powered by data from 432 Japanese wineries.">',
            "canonical": '<link rel="canonical" href="https://wine.terroirhub.com/en/wine/plans/">',
            "brand_link": '<a class="nav-logo" href="/">Terroir HUB <em>WINE</em></a>',
            "nav_search": '<a href="/en/wine/search/">Winery Search</a>',
            "nav_guide": '<a href="/en/wine/guide/">Wine Guides</a>',
            "nav_mypage": '<a href="/en/wine/mypage/">My Page</a>',
            "nav_active": '<a href="/en/wine/plans/" class="active">Plans</a>',
            "hero_tag": '<div class="hero-tag">Plans</div>',
            "hero_h1": '<h1>Start free.<br>Upgrade when you need more.</h1>',
            "hero_p": '<p>Login is free. AI sommelier Sakura is available after login. Try short sessions first, then upgrade when you need deeper support.</p>',
            "sakura_img": '<img src="/img/sakura-fullbody.png" alt="Sakura">',
            "sakura_h3": '<h3>What is AI sommelier Sakura?</h3>',
            "sakura_p": '<p>Based on data from 432 Japanese wineries, Sakura answers questions about grape varieties, regions, pairings, and winery profiles. It supports Japanese, English, and French, and works across all Terroir HUB sites with one account.</p>',
            "free_name": '<div class="card-name">Free Login</div>',
            "free_price": '<div class="card-price">¥0</div>',
            "free_desc": '<div class="card-desc">Login and My Page are free</div>',
            "free_li1": '<li class="on">Login and use My Page</li>',
            "free_li2": '<li class="on">Save items, recent searches, revisit later</li>',
            "free_li3": '<li class="on">Browse winery search and guides</li>',
            "free_li4": '<li class="on">Browse the compare hub</li>',
            "free_li5": '<li class="off">Full Sakura conversations</li>',
            "free_li6": '<li class="off">Deep multi-language support</li>',
            "free_li7": '<li class="off">Long-form reports</li>',
            "free_li8": '<li class="off">Extended session limits</li>',
            "free_btn": '<button class="card-cta cta-free" onclick="showAuth(\'signup\')">Start free</button>',
            "pro_name": '<div class="card-name">Pro</div>',
            "pro_price": '<div class="card-price">¥500<span>/mo</span></div>',
            "pro_desc": '<div class="card-desc">Daily Sakura use</div>',
            "pro_high": '<div class="card-highlight">Everything in Free Login +</div>',
            "pro_li1": '<li class="on">100 Sakura credits / month</li>',
            "pro_li2": '<li class="on">English and French conversations</li>',
            "pro_li3": '<li class="on">Deeper comparisons and recommendations</li>',
            "pro_li4": '<li class="on">Pairing and travel advice</li>',
            "pro_li5": '<li class="on">Save winery comparisons</li>',
            "pro_li6": '<li class="on">Resume conversation logs</li>',
            "pro_li7": '<li class="off">Long-form reports</li>',
            "pro_li8": '<li class="off">Higher-volume usage tier</li>',
            "pro_btn": '<button class="card-cta cta-pro" onclick="if(window.thubAuth&&window.thubAuth.isLoggedIn){thubSubscribe(\'pro\')}else{sessionStorage.setItem(\'thub_pending_plan\',\'pro\');showAuth(\'signup\')}">Start Pro</button>',
            "premium_name": '<div class="card-name">Premium</div>',
            "premium_price": '<div class="card-price">¥1,500<span>/mo</span></div>',
            "premium_desc": '<div class="card-desc">Heavy multi-language use</div>',
            "premium_high": '<div class="card-highlight">Everything in Pro +</div>',
            "premium_li1": '<li class="on">300 Sakura credits / month</li>',
            "premium_li2": '<li class="on">Detailed winery reports</li>',
            "premium_li3": '<li class="on">Cross-category comparisons</li>',
            "premium_li4": '<li class="on">Travel plans and purchase advice</li>',
            "premium_li5": '<li class="on">Buy extra credits</li>',
            "premium_li6": '<li class="on">Long and continuous conversations</li>',
            "premium_btn": '<button class="card-cta cta-premium" onclick="if(window.thubAuth&&window.thubAuth.isLoggedIn){thubSubscribe(\'premium\')}else{sessionStorage.setItem(\'thub_pending_plan\',\'premium\');showAuth(\'signup\')}">Start Premium</button>',
            "note": '<div class="plans-note"><strong>Model:</strong> Login and My Page are free. Sakura is the monthly subscription product, selected for deep conversations, comparisons, and multilingual advice.</div>',
            "secondary_note": '<p class="note">Terroir HUB can be used with one account across sake, shochu, whisky, and wine. Accounts created on <a href="https://sake.terroirhub.com">sake.terroirhub.com</a> also work here.</p>',
            "faq_title": '<h2 class="faq-title">FAQ</h2>',
            "faq1q": '<div class="faq-q" onclick="this.parentElement.classList.toggle(\'open\')">Can I cancel anytime?</div>',
            "faq1a": '<div class="faq-a">Yes. No new charge will occur after your next renewal date, and you keep access until the current period ends.</div>',
            "faq2q": '<div class="faq-q" onclick="this.parentElement.classList.toggle(\'open\')">Is Sakura free?</div>',
            "faq2a": '<div class="faq-a">Login is free, but Sakura itself is a monthly subscription. We may offer a short trial, but the real value is in the paid plan.</div>',
            "faq3q": '<div class="faq-q" onclick="this.parentElement.classList.toggle(\'open\')">Can I use the same account as the sake site?</div>',
            "faq3a": '<div class="faq-a">Yes. Terroir HUB shares one account across sake, shochu, whisky, and wine. Once you log in anywhere, you can use the wine Sakura and the credits are shared.</div>',
            "faq4q": '<div class="faq-q" onclick="this.parentElement.classList.toggle(\'open\')">How can I pay?</div>',
            "faq4a": '<div class="faq-a">We accept major credit cards through Stripe, including Visa, Mastercard, Amex, and JCB.</div>',
            "faq5q": '<div class="faq-q" onclick="this.parentElement.classList.toggle(\'open\')">Can I change plans later?</div>',
            "faq5a": '<div class="faq-a">Yes. Upgrades take effect immediately, and downgrades take effect from the next renewal date.</div>',
            "badge": '<div class="card-badge">Recommended</div>',
            "footer": '<footer class="footer">\n  &copy; 2025 FOMUS LLC — Terroir HUB WINE &nbsp;|&nbsp;\n  <a href="/privacy.html">Privacy</a> &nbsp;|&nbsp;\n  <a href="/terms.html">Terms</a>\n</footer>',
        }
    else:
        data = {
            "lang": "fr",
            "title": "<title>Tarifs — Terroir HUB WINE</title>",
            "desc": '<meta name="description" content="Tarifs Terroir HUB WINE. La connexion et Mon espace sont gratuites; Sakura, l’assistant IA, fonctionne par abonnement mensuel. Basé sur 432 domaines japonais.">',
            "canonical": '<link rel="canonical" href="https://wine.terroirhub.com/fr/wine/plans/">',
            "brand_link": '<a class="nav-logo" href="/">Terroir HUB <em>WINE</em></a>',
            "nav_search": '<a href="/fr/wine/search/">Recherche de domaines</a>',
            "nav_guide": '<a href="/fr/wine/guide/">Guides</a>',
            "nav_mypage": '<a href="/fr/wine/mypage/">Mon espace</a>',
            "nav_active": '<a href="/fr/wine/plans/" class="active">Tarifs</a>',
            "hero_tag": '<div class="hero-tag">Tarifs</div>',
            "hero_h1": '<h1>Commencez gratuitement.<br>Montez en gamme si nécessaire.</h1>',
            "hero_p": '<p>La connexion est gratuite. Sakura est disponible après connexion. Testez avec de courtes sessions, puis passez à un abonnement lorsque vous voulez aller plus loin.</p>',
            "sakura_img": '<img src="/img/sakura-fullbody.png" alt="Sakura">',
            "sakura_h3": '<h3>Qu’est-ce que Sakura ?</h3>',
            "sakura_p": '<p>Basé sur les données de 432 domaines viticoles japonais, Sakura répond sur les cépages, les régions, les accords mets-vins et les domaines. Il supporte le japonais, l’anglais et le français, et fonctionne sur tout Terroir HUB avec un seul compte.</p>',
            "free_name": '<div class="card-name">Connexion gratuite</div>',
            "free_price": '<div class="card-price">¥0</div>',
            "free_desc": '<div class="card-desc">Connexion et Mon espace gratuits</div>',
            "free_li1": '<li class="on">Connexion et utilisation de Mon espace</li>',
            "free_li2": '<li class="on">Sauvegarde, recherches récentes, reprise</li>',
            "free_li3": '<li class="on">Recherche de domaines et guides</li>',
            "free_li4": '<li class="on">Hub comparatif</li>',
            "free_li5": '<li class="off">Conversations complètes avec Sakura</li>',
            "free_li6": '<li class="off">Approfondissement multilingue</li>',
            "free_li7": '<li class="off">Rapports longs</li>',
            "free_li8": '<li class="off">Usage prolongé</li>',
            "free_btn": '<button class="card-cta cta-free" onclick="showAuth(\'signup\')">Commencer</button>',
            "pro_name": '<div class="card-name">Pro</div>',
            "pro_price": '<div class="card-price">¥500<span>/mois</span></div>',
            "pro_desc": '<div class="card-desc">Usage quotidien de Sakura</div>',
            "pro_high": '<div class="card-highlight">Tout ce qui est gratuit +</div>',
            "pro_li1": '<li class="on">100 crédits Sakura / mois</li>',
            "pro_li2": '<li class="on">Conversations en anglais et français</li>',
            "pro_li3": '<li class="on">Comparaisons et recommandations plus poussées</li>',
            "pro_li4": '<li class="on">Accords mets-vins et voyages</li>',
            "pro_li5": '<li class="on">Sauvegarde des comparaisons</li>',
            "pro_li6": '<li class="on">Reprise des conversations</li>',
            "pro_li7": '<li class="off">Rapports longs</li>',
            "pro_li8": '<li class="off">Niveau d’utilisation plus élevé</li>',
            "pro_btn": '<button class="card-cta cta-pro" onclick="if(window.thubAuth&&window.thubAuth.isLoggedIn){thubSubscribe(\'pro\')}else{sessionStorage.setItem(\'thub_pending_plan\',\'pro\');showAuth(\'signup\')}">Commencer Pro</button>',
            "premium_name": '<div class="card-name">Premium</div>',
            "premium_price": '<div class="card-price">¥1,500<span>/mois</span></div>',
            "premium_desc": '<div class="card-desc">Usage multilingue intensif</div>',
            "premium_high": '<div class="card-highlight">Tout ce qui est Pro +</div>',
            "premium_li1": '<li class="on">300 crédits Sakura / mois</li>',
            "premium_li2": '<li class="on">Rapports détaillés sur les domaines</li>',
            "premium_li3": '<li class="on">Comparaisons intercatégories</li>',
            "premium_li4": '<li class="on">Voyages et conseils d’achat</li>',
            "premium_li5": '<li class="on">Crédits supplémentaires</li>',
            "premium_li6": '<li class="on">Conversations longues et continues</li>',
            "premium_btn": '<button class="card-cta cta-premium" onclick="if(window.thubAuth&&window.thubAuth.isLoggedIn){thubSubscribe(\'premium\')}else{sessionStorage.setItem(\'thub_pending_plan\',\'premium\');showAuth(\'signup\')}">Commencer Premium</button>',
            "note": '<div class="plans-note"><strong>Modèle :</strong> La connexion et Mon espace sont gratuits. Sakura est le produit d’abonnement mensuel, pour les conversations approfondies, les comparaisons et le multilingue.</div>',
            "secondary_note": '<p class="note">Terroir HUB fonctionne avec un seul compte sur sake, shochu, whisky et vin. Les comptes créés sur <a href="https://sake.terroirhub.com">sake.terroirhub.com</a> fonctionnent aussi ici.</p>',
            "faq_title": '<h2 class="faq-title">FAQ</h2>',
            "faq1q": '<div class="faq-q" onclick="this.parentElement.classList.toggle(\'open\')">Puis-je annuler à tout moment ?</div>',
            "faq1a": '<div class="faq-a">Oui. Aucun nouveau prélèvement n’a lieu après la date de renouvellement, et l’accès reste actif jusqu’à la fin de la période en cours.</div>',
            "faq2q": '<div class="faq-q" onclick="this.parentElement.classList.toggle(\'open\')">Sakura est-il gratuit ?</div>',
            "faq2a": '<div class="faq-a">La connexion est gratuite, mais Sakura est un abonnement mensuel. Nous pouvons proposer un court essai, mais la valeur principale est dans l’offre payante.</div>',
            "faq3q": '<div class="faq-q" onclick="this.parentElement.classList.toggle(\'open\')">Puis-je utiliser le même compte que sur le site saké ?</div>',
            "faq3a": '<div class="faq-a">Oui. Terroir HUB partage un seul compte entre le saké, le shochu, le whisky et le vin. Une fois connecté, vous pouvez utiliser Sakura sur le site vin et les crédits sont partagés.</div>',
            "faq4q": '<div class="faq-q" onclick="this.parentElement.classList.toggle(\'open\')">Comment payer ?</div>',
            "faq4a": '<div class="faq-a">Nous acceptons les cartes principales via Stripe, notamment Visa, Mastercard, Amex et JCB.</div>',
            "faq5q": '<div class="faq-q" onclick="this.parentElement.classList.toggle(\'open\')">Puis-je changer de formule ensuite ?</div>',
            "faq5a": '<div class="faq-a">Oui. Les montées en gamme prennent effet immédiatement, et les baisses prennent effet à la prochaine échéance.</div>',
            "badge": '<div class="card-badge">Recommandé</div>',
            "footer": '<footer class="footer">\n  &copy; 2025 FOMUS LLC — Terroir HUB WINE &nbsp;|&nbsp;\n  <a href="/privacy.html">Confidentialité</a> &nbsp;|&nbsp;\n  <a href="/terms.html">Conditions</a>\n</footer>',
        }
    text = src
    for old, new in PLAN_COMMON:
        text = text.replace(old, new.format(**data))
    # Add hreflang block after canonical line.
    hreflang = (
        '<link rel="alternate" hreflang="ja" href="https://wine.terroirhub.com/wine/plans/">\n'
        '<link rel="alternate" hreflang="en" href="https://wine.terroirhub.com/en/wine/plans/">\n'
        '<link rel="alternate" hreflang="fr" href="https://wine.terroirhub.com/fr/wine/plans/">\n'
        '<link rel="alternate" hreflang="x-default" href="https://wine.terroirhub.com/en/wine/plans/">'
    )
    text = text.replace(data["canonical"], data["canonical"] + "\n" + hreflang)
    text = text.replace("{badge}", data["badge"])
    text = text.replace("{footer}", data["footer"])
    return text


MYPAGE_COMMON = [
    ('<html lang="ja">', '<html lang="{lang}">'),
    ('<title>マイページ | Terroir HUB WINE</title>', '{title}'),
    ('<meta name="description" content="Terroir HUB WINEのマイページ。プラン状況、最近の検索、保存したワイナリーをまとめて確認できます。">', '{desc}'),
    ('<link rel="canonical" href="https://wine.terroirhub.com/wine/mypage/">', '{canonical}'),
    ('<meta property="og:title" content="マイページ | Terroir HUB WINE">', '{og_title}'),
    ('<meta property="og:description" content="プラン状況、最近の検索、保存したワイナリーをまとめて確認できます。">', '{og_desc}'),
    ('<meta property="og:url" content="https://wine.terroirhub.com/wine/mypage/">', '{og_url}'),
    ('<a href="/" class="nav-logo">Terroir HUB <span>WINE</span></a>', '{brand_link}'),
    ('<a href="/wine/search/">検索</a>', '{nav_search}'),
    ('<a href="/wine/guide/">ガイド</a>', '{nav_guide}'),
    ('<a href="/wine/plans/">プラン</a>', '{nav_plans}'),
    ('<a href="/wine/mypage/" class="active">マイページ</a>', '{nav_active}'),
    ('<div class="eyebrow">My Page</div>', '{eyebrow}'),
    ('<h1>Terroir HUBの使い方を、ここにまとめる。</h1>', '{hero_h1}'),
    ('<p>最近の検索、保存したワイナリー、いまのプランをまとめて見られる個人ページです。PCでもスマホでも、次に開く場所がすぐ分かるようにしています。</p>', '{hero_p}'),
    ('<a class="chip" href="/wine/search/">ワイナリー検索</a>', '{chip1}'),
    ('<a class="chip" href="/wine/guide/compare.html">比較ハブ</a>', '{chip2}'),
    ('<a class="chip" href="/wine/guide/beginner.html">初心者ガイド</a>', '{chip3}'),
    ('<a class="chip" href="/wine/plans/">プラン確認</a>', '{chip4}'),
    ('<a class="chip" href="/wine/search/">無料ログイン</a>', '{hero_chip1}'),
    ('<a class="chip" href="/wine/plans/">Sakura月額</a>', '{hero_chip2}'),
    ('<h2>サクラ</h2>', '{sakura_h2}'),
    ('<p>ログイン後に使う、多言語対応の日本酒・焼酎・ワイン・ウイスキー横断チャット。</p>', '{sakura_p}'),
    ('<div class="track-card"><strong>Free</strong><span>マイページ</span></div>', '{track1}'),
    ('<div class="track-card"><strong>Pro</strong><span>本格相談</span></div>', '{track2}'),
    ('<div class="track-card"><strong>Premium</strong><span>深掘り利用</span></div>', '{track3}'),
    ('<p class="side-note">無料ログインで保存と履歴を持ち、Sakuraは月額で深掘り。ここが課金導線の中心です。</p>', '{side_note}'),
    ('<button class="btn btn-primary" onclick="showAuth(\'login\')">ログイン</button>', '{login_btn}'),
    ('<a class="btn btn-outline" href="/wine/plans/">プランを見る</a>', '{plans_btn}'),
    ('<a class="btn btn-outline" href="/wine/search/">検索へ戻る</a>', '{search_btn}'),
    ('<div style="font-size:12px;color:rgba(255,255,255,.55);margin-bottom:8px;letter-spacing:.08em;text-transform:uppercase;">Terroir HUB</div>', '{hub_label}'),
    ('<strong>SAKE</strong><span>酒蔵検索とAIサクラを横断利用</span>', '{site1}'),
    ('<strong>SHOCHU</strong><span>焼酎・泡盛の造り手を探す</span>', '{site2}'),
    ('<strong>WHISKY</strong><span>蒸留所と銘柄を比べる</span>', '{site3}'),
    ('<strong>WINE</strong><span>比較ハブと保存を使いこなす</span>', '{site4}'),
    ('<div class="notice">\n    マイページは、この端末で見た内容をすばやく戻るための場所です。保存ボタンで候補を残し、検索履歴からもう一度絞り込み、必要なときだけSakuraを月額で深掘りする流れにすると使いやすくなります。\n  </div>', '{notice}'),
    ('<h3>保存したワイナリー</h3>', '{saved_h3}'),
    ('<div class="sub">検索ページの保存ボタンで追加されます。</div>', '{saved_sub}'),
    ('<h3>最近の検索</h3>', '{recent_h3}'),
    ('<div class="sub">前回見たキーワードをすぐ再利用できます。</div>', '{recent_sub}'),
    ('<div class="muted" id="recentEmpty" style="display:none;">まだ履歴がありません。検索ページで調べるとここに残ります。</div>', '{recent_empty}'),
    ('<h3>次に開くページ</h3>', '{next_h3}'),
    ('<a class="chip" href="/wine/guide/beginner.html">初心者ガイド</a>', '{next1}'),
    ('<a class="chip" href="/wine/guide/compare.html">比較ハブ</a>', '{next2}'),
    ('<a class="chip" href="/wine/guide/visit.html">見学ガイド</a>', '{next3}'),
    ('<a class="chip" href="/wine/guide/koshu.html">甲州</a>', '{next4}'),
    ('<a class="chip" href="/wine/guide/yamanashi-vs-nagano.html">山梨 vs 長野</a>', '{next5}'),
    ('<a href="/wine/search/">検索</a> ・ <a href="/wine/guide/">ガイド</a> ・ <a href="/wine/plans/">プラン</a>', '{footer_links}'),
    ("alert('マイページに保存しました');", "{alert_text}"),
    ('<div class="empty">まだ保存されたワイナリーはありません。検索結果の「保存」から追加できます。</div>', '{saved_empty}'),
    ('<div class="status-card"><strong>ログイン状態</strong><span id="mp-login">確認中</span></div>', '{status_login}'),
    ('<div class="status-card"><strong>プラン</strong><span id="mp-plan">確認中</span></div>', '{status_plan}'),
    ('<div class="status-card"><strong>残クレジット</strong><span id="mp-credits">確認中</span></div>', '{status_credits}'),
    ('<div class="status-card"><strong>保存件数</strong><span id="mp-saved">0件</span></div>', '{status_saved}'),
    ('<script type="application/ld+json">\n{"@context":"https://schema.org","@type":"WebPage","name":"マイページ","description":"Terroir HUB WINEのマイページ。","url":"https://wine.terroirhub.com/wine/mypage/","isPartOf":{"@type":"WebSite","name":"Terroir HUB WINE","url":"https://wine.terroirhub.com/"}}\n</script>', '{jsonld}'),
    ("document.getElementById('mp-saved').textContent = saved.length + '件';", '{saved_count_js}'),
    ("'<div class=\"item-main\"><strong>' + escapeHtml(item.name || '—') + '</strong><span>' + escapeHtml([item.pref, item.area].filter(Boolean).join(' / ') || '保存済み') + '</span></div>' +", '{saved_item_meta}'),
    ("<a href=\"' + escapeHtml(item.page || '#') + '\">開く</a>", '{saved_item_open}'),
    ("loginEl.textContent = '未接続';", '{login_disconnected}'),
    ("loginEl.textContent = '未ログイン';", '{login_logged_out}'),
    ("loginEl.textContent = 'ログイン中';", '{login_logged_in}'),
    ("loginEl.textContent = '確認失敗';", '{login_failed}'),
    ("creditsEl.textContent = bonus ? bonus + '枚' : '0';", '{credits_text}'),
]


def build_mypage(lang: str) -> str:
    src = read(BASE / "wine" / "mypage" / "index.html")
    if lang == "en":
        data = {
            "lang": "en",
            "title": "<title>My Page | Terroir HUB WINE</title>",
            "desc": '<meta name="description" content="Terroir HUB WINE My Page. View your plan status, recent searches, and saved wineries in one place.">',
            "canonical": '<link rel="canonical" href="https://wine.terroirhub.com/en/wine/mypage/">',
            "og_title": '<meta property="og:title" content="My Page | Terroir HUB WINE">',
            "og_desc": '<meta property="og:description" content="View your plan status, recent searches, and saved wineries in one place.">',
            "og_url": '<meta property="og:url" content="https://wine.terroirhub.com/en/wine/mypage/">',
            "brand_link": '<a href="/en/" class="nav-logo">Terroir HUB <span>WINE</span></a>',
            "nav_search": '<a href="/en/wine/search/">Search</a>',
            "nav_guide": '<a href="/en/wine/guide/">Guides</a>',
            "nav_plans": '<a href="/en/wine/plans/">Plans</a>',
            "nav_active": '<a href="/en/wine/mypage/" class="active">My Page</a>',
            "eyebrow": '<div class="eyebrow">My Page</div>',
            "hero_h1": '<h1>Keep your Terroir HUB activity in one place.</h1>',
            "hero_p": '<p>This personal page collects recent searches, saved wineries, and your current plan. It is designed so you always know what to open next, on desktop or mobile.</p>',
            "chip1": '<a class="chip" href="/en/wine/search/">Search wineries</a>',
            "chip2": '<a class="chip" href="/en/wine/guide/compare.html">Compare hub</a>',
            "chip3": '<a class="chip" href="/en/wine/guide/beginner.html">Beginner guide</a>',
            "chip4": '<a class="chip" href="/en/wine/plans/">Check plan</a>',
            "sakura_h2": '<h2>Sakura</h2>',
            "sakura_p": '<p>A multilingual chat assistant for Japanese sake, shochu, wine, and whisky. Available after login.</p>',
            "track1": '<div class="track-card"><strong>Free</strong><span>My Page</span></div>',
            "track2": '<div class="track-card"><strong>Pro</strong><span>Deep support</span></div>',
            "track3": '<div class="track-card"><strong>Premium</strong><span>Advanced use</span></div>',
            "hero_chip1": '<a class="chip" href="/en/wine/search/">Free login</a>',
            "hero_chip2": '<a class="chip" href="/en/wine/plans/">Sakura monthly</a>',
            "side_note": '<p class="side-note">Free login keeps your saves and history. Sakura is the monthly paid layer for deeper questions.</p>',
            "login_btn": '<button class="btn btn-primary" onclick="showAuth(\'login\')">Log in</button>',
            "plans_btn": '<a class="btn btn-outline" href="/en/wine/plans/">See plans</a>',
            "search_btn": '<a class="btn btn-outline" href="/en/wine/search/">Back to search</a>',
            "hub_label": '<div style="font-size:12px;color:rgba(255,255,255,.55);margin-bottom:8px;letter-spacing:.08em;text-transform:uppercase;">Terroir HUB</div>',
            "site1": '<strong>SAKE</strong><span>Search breweries and use Sakura</span>',
            "site2": '<strong>SHOCHU</strong><span>Explore shochu and awamori makers</span>',
            "site3": '<strong>WHISKY</strong><span>Compare distilleries and bottles</span>',
            "site4": '<strong>WINE</strong><span>Use the compare hub and saved list</span>',
            "notice": '<div class="notice">My Page is where you return quickly to what you already found. Save candidates from search, revisit them from history, and upgrade to Sakura only when you need deeper guidance.</div>',
            "saved_h3": '<h3>Saved wineries</h3>',
            "saved_sub": '<div class="sub">Added from the Save button on search results.</div>',
            "recent_h3": '<h3>Recent searches</h3>',
            "recent_sub": '<div class="sub">Reuse your previous search terms instantly.</div>',
            "recent_empty": '<div class="muted" id="recentEmpty" style="display:none;">No history yet. Search something and it will appear here.</div>',
            "next_h3": '<h3>Next pages to open</h3>',
            "next1": '<a class="chip" href="/en/wine/guide/beginner.html">Beginner guide</a>',
            "next2": '<a class="chip" href="/en/wine/guide/compare.html">Compare hub</a>',
            "next3": '<a class="chip" href="/en/wine/guide/visit.html">Visit guide</a>',
            "next4": '<a class="chip" href="/en/wine/guide/koshu.html">Koshu</a>',
            "next5": '<a class="chip" href="/en/wine/guide/yamanashi-vs-nagano.html">Yamanashi vs Nagano</a>',
            "footer_links": '<a href="/en/wine/search/">Search</a> ・ <a href="/en/wine/guide/">Guides</a> ・ <a href="/en/wine/plans/">Plans</a>',
            "alert_text": "showToast('Saved to My Page');",
            "saved_empty": '<div class="empty">No saved wineries yet. Use Save on a search result to add one.</div>',
            "login_state": '<span id="mp-login">Checking</span>',
            "plan_state": '<span id="mp-plan">Checking</span>',
            "credits_state": '<span id="mp-credits">Checking</span>',
            "saved_state": '<span id="mp-saved">0</span>',
            "jsonld": '<script type="application/ld+json">\n{"@context":"https://schema.org","@type":"WebPage","name":"My Page","description":"Terroir HUB WINE My Page. View your plan status, recent searches, and saved wineries in one place.","url":"https://wine.terroirhub.com/en/wine/mypage/","isPartOf":{"@type":"WebSite","name":"Terroir HUB WINE","url":"https://wine.terroirhub.com/"}}\n</script>',
            "status_login": '<div class="status-card"><strong>Login status</strong><span id="mp-login">Checking</span></div>',
            "status_plan": '<div class="status-card"><strong>Plan</strong><span id="mp-plan">Checking</span></div>',
            "status_credits": '<div class="status-card"><strong>Credits</strong><span id="mp-credits">Checking</span></div>',
            "status_saved": '<div class="status-card"><strong>Saved items</strong><span id="mp-saved">0</span></div>',
            "saved_count_js": "document.getElementById('mp-saved').textContent = saved.length + ' items';",
            "saved_item_meta": "'<div class=\"item-main\"><strong>' + escapeHtml(item.name || '—') + '</strong><span>' + escapeHtml([item.pref, item.area].filter(Boolean).join(' / ') || 'Saved') + '</span></div>' +",
            "saved_item_open": "<a href=\"' + escapeHtml(item.page || '#') + '\">Open</a>",
            "login_disconnected": "loginEl.textContent = 'Disconnected';",
            "login_logged_out": "loginEl.textContent = 'Logged out';",
            "login_logged_in": "loginEl.textContent = 'Logged in';",
            "login_failed": "loginEl.textContent = 'Check failed';",
            "credits_text": "creditsEl.textContent = bonus ? bonus + ' credits' : '0';",
        }
    else:
        data = {
            "lang": "fr",
            "title": "<title>Mon espace | Terroir HUB WINE</title>",
            "desc": '<meta name="description" content="Mon espace Terroir HUB WINE. Consultez votre abonnement, vos recherches récentes et vos domaines enregistrés en un seul endroit.">',
            "canonical": '<link rel="canonical" href="https://wine.terroirhub.com/fr/wine/mypage/">',
            "og_title": '<meta property="og:title" content="Mon espace | Terroir HUB WINE">',
            "og_desc": '<meta property="og:description" content="Consultez votre abonnement, vos recherches récentes et vos domaines enregistrés en un seul endroit.">',
            "og_url": '<meta property="og:url" content="https://wine.terroirhub.com/fr/wine/mypage/">',
            "brand_link": '<a href="/fr/" class="nav-logo">Terroir HUB <span>WINE</span></a>',
            "nav_search": '<a href="/fr/wine/search/">Recherche</a>',
            "nav_guide": '<a href="/fr/wine/guide/">Guides</a>',
            "nav_plans": '<a href="/fr/wine/plans/">Tarifs</a>',
            "nav_active": '<a href="/fr/wine/mypage/" class="active">Mon espace</a>',
            "eyebrow": '<div class="eyebrow">Mon espace</div>',
            "hero_h1": '<h1>Gardez votre activité Terroir HUB au même endroit.</h1>',
            "hero_p": '<p>Cette page personnelle regroupe vos recherches récentes, vos domaines enregistrés et votre formule actuelle. Vous savez toujours quoi ouvrir ensuite, sur ordinateur ou mobile.</p>',
            "chip1": '<a class="chip" href="/fr/wine/search/">Rechercher des domaines</a>',
            "chip2": '<a class="chip" href="/fr/wine/guide/compare.html">Hub comparatif</a>',
            "chip3": '<a class="chip" href="/fr/wine/guide/beginner.html">Guide débutant</a>',
            "chip4": '<a class="chip" href="/fr/wine/plans/">Voir les tarifs</a>',
            "sakura_h2": '<h2>Sakura</h2>',
            "sakura_p": '<p>Assistant de conversation multilingue pour le saké, le shochu, le vin et le whisky japonais. Disponible après connexion.</p>',
            "track1": '<div class="track-card"><strong>Free</strong><span>Mon espace</span></div>',
            "track2": '<div class="track-card"><strong>Pro</strong><span>Aide approfondie</span></div>',
            "track3": '<div class="track-card"><strong>Premium</strong><span>Usage avancé</span></div>',
            "hero_chip1": '<a class="chip" href="/fr/wine/search/">Connexion gratuite</a>',
            "hero_chip2": '<a class="chip" href="/fr/wine/plans/">Sakura mensuel</a>',
            "side_note": '<p class="side-note">La connexion gratuite conserve vos favoris et votre historique. Sakura est la couche payante mensuelle pour les questions approfondies.</p>',
            "login_btn": '<button class="btn btn-primary" onclick="showAuth(\'login\')">Connexion</button>',
            "plans_btn": '<a class="btn btn-outline" href="/fr/wine/plans/">Voir les tarifs</a>',
            "search_btn": '<a class="btn btn-outline" href="/fr/wine/search/">Retour à la recherche</a>',
            "hub_label": '<div style="font-size:12px;color:rgba(255,255,255,.55);margin-bottom:8px;letter-spacing:.08em;text-transform:uppercase;">Terroir HUB</div>',
            "site1": '<strong>SAKE</strong><span>Rechercher des brasseries et utiliser Sakura</span>',
            "site2": '<strong>SHOCHU</strong><span>Explorer les producteurs de shochu et awamori</span>',
            "site3": '<strong>WHISKY</strong><span>Comparer distilleries et bouteilles</span>',
            "site4": '<strong>WINE</strong><span>Hub comparatif et favoris enregistrés</span>',
            "notice": '<div class="notice">Mon espace vous permet de revenir rapidement à ce que vous avez déjà trouvé. Enregistrez des candidats depuis la recherche, retrouvez-les dans l’historique, et passez à Sakura uniquement quand vous avez besoin d’aller plus loin.</div>',
            "saved_h3": '<h3>Domaines enregistrés</h3>',
            "saved_sub": '<div class="sub">Ajoutés via le bouton Enregistrer sur la recherche.</div>',
            "recent_h3": '<h3>Recherches récentes</h3>',
            "recent_sub": '<div class="sub">Réutilisez instantanément vos derniers mots-clés.</div>',
            "recent_empty": '<div class="muted" id="recentEmpty" style="display:none;">Aucun historique pour le moment. Lancez une recherche et elle apparaîtra ici.</div>',
            "next_h3": '<h3>Pages à ouvrir ensuite</h3>',
            "next1": '<a class="chip" href="/fr/wine/guide/beginner.html">Guide débutant</a>',
            "next2": '<a class="chip" href="/fr/wine/guide/compare.html">Hub comparatif</a>',
            "next3": '<a class="chip" href="/fr/wine/guide/visit.html">Guide visite</a>',
            "next4": '<a class="chip" href="/fr/wine/guide/koshu.html">Koshu</a>',
            "next5": '<a class="chip" href="/fr/wine/guide/yamanashi-vs-nagano.html">Yamanashi vs Nagano</a>',
            "footer_links": '<a href="/fr/wine/search/">Recherche</a> ・ <a href="/fr/wine/guide/">Guides</a> ・ <a href="/fr/wine/plans/">Tarifs</a>',
            "alert_text": "showToast('Enregistré dans Mon espace');",
            "saved_empty": '<div class="empty">Aucun domaine enregistré pour le moment. Utilisez Enregistrer sur un résultat pour l’ajouter.</div>',
            "login_state": '<span id="mp-login">Vérification</span>',
            "plan_state": '<span id="mp-plan">Vérification</span>',
            "credits_state": '<span id="mp-credits">Vérification</span>',
            "saved_state": '<span id="mp-saved">0</span>',
            "jsonld": '<script type="application/ld+json">\n{"@context":"https://schema.org","@type":"WebPage","name":"Mon espace","description":"Mon espace Terroir HUB WINE. Consultez votre abonnement, vos recherches récentes et vos domaines enregistrés en un seul endroit.","url":"https://wine.terroirhub.com/fr/wine/mypage/","isPartOf":{"@type":"WebSite","name":"Terroir HUB WINE","url":"https://wine.terroirhub.com/"}}\n</script>',
            "status_login": '<div class="status-card"><strong>État de connexion</strong><span id="mp-login">Vérification</span></div>',
            "status_plan": '<div class="status-card"><strong>Formule</strong><span id="mp-plan">Vérification</span></div>',
            "status_credits": '<div class="status-card"><strong>Crédits restants</strong><span id="mp-credits">Vérification</span></div>',
            "status_saved": '<div class="status-card"><strong>Enregistrements</strong><span id="mp-saved">0</span></div>',
            "saved_count_js": "document.getElementById('mp-saved').textContent = saved.length + ' éléments';",
            "saved_item_meta": "'<div class=\"item-main\"><strong>' + escapeHtml(item.name || '—') + '</strong><span>' + escapeHtml([item.pref, item.area].filter(Boolean).join(' / ') || 'Enregistré') + '</span></div>' +",
            "saved_item_open": "<a href=\"' + escapeHtml(item.page || '#') + '\">Ouvrir</a>",
            "login_disconnected": "loginEl.textContent = 'Déconnecté';",
            "login_logged_out": "loginEl.textContent = 'Déconnecté';",
            "login_logged_in": "loginEl.textContent = 'Connecté';",
            "login_failed": "loginEl.textContent = 'Échec de vérification';",
            "credits_text": "creditsEl.textContent = bonus ? bonus + ' crédits' : '0';",
        }
    text = src
    for old, new in MYPAGE_COMMON:
        text = text.replace(old, new.format(**data))
    text = text.replace(
        '<link rel="canonical" href="https://wine.terroirhub.com/wine/mypage/">',
        data["canonical"] + "\n<link rel=\"alternate\" hreflang=\"ja\" href=\"https://wine.terroirhub.com/wine/mypage/\">\n<link rel=\"alternate\" hreflang=\"en\" href=\"https://wine.terroirhub.com/en/wine/mypage/\">\n<link rel=\"alternate\" hreflang=\"fr\" href=\"https://wine.terroirhub.com/fr/wine/mypage/\">\n<link rel=\"alternate\" hreflang=\"x-default\" href=\"https://wine.terroirhub.com/en/wine/mypage/\">"
    )
    return text


def main():
    for lang in ("en", "fr"):
        write(BASE / lang / "wine" / "search" / "index.html", build_search(lang))
        write(BASE / lang / "wine" / "plans" / "index.html", build_plans(lang))
        write(BASE / lang / "wine" / "mypage" / "index.html", build_mypage(lang))
    print("Localized UI pages generated")


if __name__ == "__main__":
    main()
